--- #YAML:1.0
name:                WWW-Twilio-API
version:             0.15
abstract:            Accessing Twilio's REST API with Perl
license:             ~
author:              
    - Scott Wiersdorf <scott@perlcode.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Crypt::SSLeay:                 0.51
    LWP::UserAgent:                2.03
    URI::Escape:                   3.28
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
