---
abstract: "Accessing Twilio's REST API with Perl"
author:
  - 'Scott Wiersdorf <scott@perlcode.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Twilio-API
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::SSLeay: 0.51
  LWP::UserAgent: 2.03
  URI::Escape: 3.28
version: 0.18
